framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - catch_previous_exception.middleware
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async: '%env(EVENT_MESSAGE_TRANSPORT_DSN)%'
#             sync: 'sync://'Ą
            # failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
             'App\Shared\Application\Event\AsyncEventInterface': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
